backend:
  name: git-gateway
  repo: kardsZero/DecapWeb
  branch: main
  auth_type: pkce
  base_url: https://auth.decapbridge.com
  auth_endpoint: /sites/b643cdd3-40de-4238-bbb3-a3005fa2a4e7/pkce
  auth_token_endpoint: /sites/b643cdd3-40de-4238-bbb3-a3005fa2a4e7/token
  gateway_url: https://gateway.decapbridge.com

auth:
  email_claim: email
  first_name_claim: first_name
  last_name_claim: last_name
  avatar_url_claim: avatar_url

site_url: https://decapweb.netlify.app

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: about
    label: About Page
    files:
      - file: content/about.md
        label: About
        name: about
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }

  - name: gallery
    label: Gallery Page
    files:
      - file: content/gallery.md
        label: Gallery
        name: gallery
        fields:
          - { label: Title, name: title, widget: string }

          - label: Images
            name: gallery
            widget: list
            field:
              label: Image
              name: image
              widget: image
 